import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {process.env.ACTIVATE_ANALYTICS === '1' && (
          <Script
            strategy='afterInteractive'
            src='https://umami.cherfaoui.dev/script.js'
            data-website-id='f0869fc8-4b69-456c-a09e-f685779acb64'
          />
        )}
        {children}
      </body>
    </html>
  );
}
